---
services:
  kafka:
    image: apache/kafka:3.7.1
    ports:
      - 9092:9092

  collector:
    image: otel/opentelemetry-collector:0.105.0
    ports:
      - 4318:4318
    volumes:
      - ./resources/collector.yml:/etc/otelcol/config.yaml

  prom:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./resources/prom.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000